# Generated by Django 2.2.1 on 2019-06-01 20:37

import AMS.managers
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('acquisition_date', models.DateField(default=datetime.date.today)),
                ('asset_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('asset_type', models.CharField(choices=[('Automobile', 'Automobile'), ('AV Equipment', 'AV Equipment'), ('Computer Equipment', 'Computer Equipment'), ('Office Furniture & Stationary', 'Office Furniture & Stationary')], max_length=30)),
                ('asset_barcode', models.CharField(blank=True, max_length=30)),
                ('asset_serial_number', models.CharField(blank=True, max_length=80)),
                ('asset_status', models.CharField(choices=[('Working', 'Working'), ('Disabled', 'Disabled')], max_length=10)),
                ('asset_department', models.CharField(max_length=50)),
                ('added_date', models.DateField(default=datetime.date.today)),
                ('modified_date', models.DateField(default=datetime.date.today)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=200.0, max_digits=19)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('current_value', models.DecimalField(decimal_places=2, default=200.0, max_digits=19)),
                ('life_expectancy', models.IntegerField(default=3)),
                ('depr_model', models.CharField(choices=[('Straight Line', 'Straight Line'), ('Double-Declining Balance', 'Double-Declining Balance'), ('Sum of Years', 'Sum of Years')], default='Straight Line', max_length=30)),
                ('currentVal_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('building', models.TextField(blank=True, max_length=1000)),
                ('floor', models.CharField(max_length=3)),
                ('adress', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_manager', models.BooleanField(default=False, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', AMS.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AMS.Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AMS.Location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
