# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 04:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('acquisition_date', models.DateField(default=datetime.date.today)),
                ('asset_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('asset_type', models.CharField(choices=[('Automobile', 'Automobile'), ('AV Equipment', 'AV Equipment'), ('Computer Equipment', 'Computer Equipment'), ('Office Furniture & Stationary', 'Office Furniture & Stationary')], max_length=30)),
                ('asset_barcode', models.CharField(blank=True, max_length=30)),
                ('asset_serial_number', models.CharField(blank=True, max_length=80)),
                ('asset_status', models.CharField(choices=[('Working', 'Working'), ('Disabled', 'Disabled')], max_length=10)),
                ('asset_owner', models.CharField(max_length=50)),
                ('asset_department', models.CharField(max_length=50)),
                ('added_date', models.DateField(default=datetime.date.today)),
                ('modified_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('building', models.TextField(blank=True, max_length=1000)),
                ('floor', models.CharField(max_length=3)),
                ('adress', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Location'),
        ),
    ]
