# Generated by Django 2.2 on 2019-04-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AMS.Location'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AMS.Asset'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
