# Generated by Django 2.2.2 on 2019-06-29 12:46

import AMS.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0002_auto_20190622_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='AMS.Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[AMS.validators.check_negative_number]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(max_length=200, validators=[AMS.validators.validate_characters]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='life_expectancy',
            field=models.IntegerField(default=3, validators=[AMS.validators.check_negative_number, AMS.validators.check_zero_number]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=19, validators=[AMS.validators.check_negative_number, AMS.validators.check_zero_number]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='residual_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[AMS.validators.check_negative_number]),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(max_length=3, validators=[AMS.validators.validate_characters]),
        ),
    ]
