# Generated by Django 2.2.2 on 2019-06-15 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0002_auto_20190609_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_department',
            field=models.CharField(choices=[('I.T', 'I.T'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Modification',
        ),
    ]
