# Generated by Django 2.2.2 on 2019-06-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0003_auto_20190629_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AMS.Location'),
        ),
    ]
