# Generated by Django 2.2.4 on 2019-08-05 12:03

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190622_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[user.validators.validate_characters], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True, validators=[user.validators.validate_employ], verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[user.validators.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[user.validators.validate_name], verbose_name='last name'),
        ),
    ]
